### ISSUE TITLE
SMS issues

### ISSUE THREAD

**Issue by larsemil** [Bajoja/indicator-kdeconnect#102]
Two questions about sms:
* Is there no way to read the contacts for sms from the phone instead of from google? I use different contacts backend and cannot utilize this.

* When writing or responding to sms it does not end upp in my sms applications a sent sms. Is this possible to fix? 

Thanks for an otherwise awesome application.

**Comment by MarkoIndaco** [comment]
Nice question. It would be useful if kdeconnect access directly to the phonebook or, at least, read a previous **.vcf file**, saved into the the phone.

**Comment by Bajoja** [comment]
@larsemil 
1 - Is not possible to read contacts from the phone, because KDEConnect Android application don't provide any interface via DBus for that.

2 - Well in my phone that not happend, this is the first time some one reporting it, when i have time i will check this.

@MarkoIndaco 
It' s possible to do what you say and it's possible to support others contacts backend, but at the moment  i don't have time to do this, if someone want to do that it will be welcome.

**Comment by MarkoIndaco** [comment]
Hey, thanks for reply. I solved my issue right now. problem was that I had not yet accepted the request to read the contacts by Google. :grinning: 

@larsemil if you wanna try this: click on **Send SMS** then on the refresh icon close to the **[Send]** button. Wait the browser open the page and grant the premission asked by KDE to Google (shuold be appear a blank page with a line about succes or not). If success you can close browser. From now, when you click on **Send SMS** you have you're contact list there but, the contact list **it's not visible until you type the first letter (not number) inside the field** :grimacing:

Greetings

**Comment by larsemil** [comment]
@MarkoIndaco i dont use google for my contacts so even if i do it will not download any contacts.

@Bajoja then i will make an issue for the android application as well so we can get the phonebook over dbus.

**Comment by andyholmes** [comment]
@larsemil Best to ask on the [kdeconnect mailing list](https://mail.kde.org/mailman/listinfo/kdeconnect), you'll get a quicker answer and an explanation if they don't want to implement it.
