### ISSUE TITLE
how to debug / find logs

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [Bajoja/indicator-kdeconnect#117]
Hi,

I have been using kdeconnect on ubuntu for a while now and I seem to have run into some issues that make it unusable.

Normally I might be able to figure it out on my own without having to ask here but I can't seem to find the logs nor to find a "debug" argument when running it.

Am I missing something ?

edit : it seems to have stopped working at the same time as my syncthing setup, and their github talks about regression in a recent python package or something... so your logs would really help me

**Comment by andyholmes** [comment]
Without building a full debug build of KDE Connect, there isn't really a debug mode. Any errors should be logged in `journalctl`/`syslog` or as stated on the [KDE Connect wiki](https://community.kde.org/KDEConnect) you can run:

    killall -9 kdeconnectd; /usr/lib/libexec/kdeconnectd -platform offscreen

to force it to run in a terminal. Otherwise, you may want to ask on the [mailinglist](https://mail.kde.org/mailman/listinfo/kdeconnect), where they will no doubt be aware of any problems with dependencies. As far as I know `indicator-kdeconnect` itself has no logs since it's just a DBus client for KDE Connect, but if that's where you think the problem is you could also try running:

    killall -9 indicator-kdeconnect; indicator-kdeconnect

And see if any errors are printed the terminal.

**Comment by thiswillbeyourgithub** [comment]
Hmm. That might explain why in the morning I had a 5GB `syslog` file... Unfortunately I was dumb enough to remove it without looking inside so I can't be sure.

When trying `killall -9 kdeconnectd; /usr/lib//kdeconnect-cli -platform offscreen` it returns `kdeconnectd: no process found` because the only package I have seem to be `kdeconnect-cli` and `kdeconnect-send`.

Did I install it wrong ? I recall installing it via a simple `apt-get`.

**Comment by andyholmes** [comment]
`kdeconnectd` isn't in `PATH`, if i recall correctly (I don't actually have it installed). If you run `locate kdeconnectd` that should tell you where it is, and you should be able to run it *directly* from that path using the above command.

`kdeconnect-cli` on the other hand is just a simple program for sending one-off commands to the server, mostly for scripting purposes.

**Comment by thiswillbeyourgithub** [comment]
Oh indeed, mine was in `/usr/lib/x86_64-linux-gnu/libexec/kdeconnectd`.

Apparently I just fixed my problem, it was a firewall misconfiguration on my end. Sorry for taking your time :/ But logs and debugging would be great :) !
