### ISSUE TITLE
use gnome contacts to select a phone number

### ISSUE THREAD

**Issue by bil-elmoussaoui** [Bajoja/indicator-kdeconnect#28]
I know the application is based on kdeconnect, but if it's possible to select a phone number instead of typing the number all by myself. Also, a better ui would be more than welcome. If you can use a Gtk.HeaderBar where you place the send/and the cancel button, it should be just perfect! 
Here's a small preview of what i did on my work on Gnome Bullet (a Pushbullet gui for gnome)
![](https://lh3.googleusercontent.com/CfsUShnYtkucCUojNOS352zkpQXT8aWPY1BG7jSqGa4w6a-CgU_gbHHIia8l5KTarNhucBAYLQeXZg=w1366-h768-rw-no)
Thanks! and it works perfectly ;) 

If you need any help on this i'm here ;)

**Comment by Bajoja** [comment]
@bil-elmoussaoui thanks, the commit i make is just a preview to test the send sms feature, i'm not good in design ui, that's why i use this simple one. 
Use gnome contacts or other one will be great and more intuitive.
I like the ui you make for push bullet, so if you contribute with that ui and your code for get contact from gnome contacts would be great.

Here is what was my initial ideia, kkkkk.
![sms](https://cloud.githubusercontent.com/assets/10621831/21853299/79c45bb0-d80e-11e6-9e31-6b20c363b4ec.png)

**Comment by Bajoja** [comment]
@bil-elmoussaoui any news?

**Comment by fitojb** [comment]
> Here is what was my initial ideia, kkkkk.

@Bajoja I think you’ll want to move the field’s labels over the fields instead of placing them to the left, because right now there’s a lot of empty space there, which will become bigger in translated versions.

**Comment by Bajoja** [comment]
@fitojb yah, I noticed that, I'm thinking of doing as you said or making the labels align

**Comment by bil-elmoussaoui** [comment]
I will take care of this as soon as possible, quite busy those days!

**Comment by Bajoja** [comment]
Ok

**Comment by OzymandiasTheGreat** [comment]
I propose temporary solution in the form of [small python script](https://github.com/OzymandiasTheGreat/send-sms). It doesn't use gnome contacts ('cause I don't use gnome contacts) but it syncs with Google Contacts and provides autocomplete for names and numbers.

**Comment by Bajoja** [comment]
Moving this to #48
