### ISSUE TITLE
Hiding unpaired devices

### ISSUE THREAD

**Issue by BenjaminNavarro** [Bajoja/indicator-kdeconnect#68]
Would it be possible to add an option to hide unpaired devices? I use it at work and so all devices on the network are displayed in my menu bar which can be a bit annoying. 

I'm okay to work on the code but can you point me in the right direction?

Thanks

**Comment by Bajoja** [comment]
@BenjaminNavarro, yeh, i'm notice that and make this is not the problem, but rather where to add this, because I do not want to create a settings panel.

One option would be to add an option to unpaired devices to hide them, but then would have to find a way to bring them back without having to create a settings panel.

I'll think about it.

**Comment by BenjaminNavarro** [comment]
One solution would be to add a menu entry on all devices with "show/hide unpaired devices"

**Comment by Bajoja** [comment]
I analyse the options and made a settings panel will be the best way since I found other things to put there.

**Comment by BenjaminNavarro** [comment]
If other configuration options are needed, a setting panel is the way to go

**Comment by Bajoja** [comment]
@BenjaminNavarro, i will make a commit, test it and give me your feedback

**Comment by BenjaminNavarro** [comment]
It's working for me, thanks for that!
