### ISSUE TITLE
Incoming SMS notification does not display Phone/Contact

### ISSUE THREAD

**Issue by derekatkins** [Bajoja/indicator-kdeconnect#83]
Hi,
When I receive an SMS message, I get the notification popup, but it lists the phone ID and message but not the contact phone/name.  So I don't know who it is unless/until I hit "reply".
I'm in Xfce in case that matters.

I just noticed that I actually get *TWO* popup notifications.  One which DOES contain the SMS message+sender, but it disappears after a few seconds.  And then a second one, which does not disappear, which just says [Phone ID] [Reply] without giving any indication of who I'm replying to or what they said.

**Comment by Bajoja** [comment]
I don't know how notifications work on Xface, but probably is a notification issue on Xface, and indicator-kdeconnect don't manage notifications, so this kind of bug need to be reported to kdeconect developers

**Comment by derekatkins** [comment]
Okay, if indicator isn't managing the Linux UI notifications, what DOES indicator do?

**Comment by andyholmes** [comment]
@derekatkins mostly the kde connect daemon does everything involving receiving. The indicator is mostly for _initiating_ actions like sending files, or SMS. I think the reason you get two is because KDE Connect tries first to use the Telepathy framework (messaging) and then the Notify framework (notifications), somehow both are being triggered, definitely a KDE Connect bug though.

@Bajoja I think you can turn this off with `kdeconnectd -platform offscreen`, I might do this if I put kdeconnect support in my gnome shell extension so I can deal with them myself.

**Comment by Bajoja** [comment]
@andyholmes thanks this info will be usefull for the user, maybe i add it to the indicator-kdeconnect-settings.

@derekatkins this indicator do what kdeconnect don't do on your DE, wich is ...
