### ISSUE TITLE
wrong icon in elementaryOS

### ISSUE THREAD

**Issue by MrSadnes** [Bajoja/indicator-kdeconnect#9]
In elementary, the indicator icon does not use the symbolic icon, making it ugly and inconsistent with the system, like this :

![captura de tela de 2016-11-27 15 54 28](https://cloud.githubusercontent.com/assets/21296444/20650621/df3e6080-b4b9-11e6-8353-879060a80cab.png)

**Comment by varlesh** [comment]
kde-connect version?

**Comment by varlesh** [comment]
elementary use libappindicator and not symbolic icons.

**Comment by varlesh** [comment]
for libappindiactor available icons (ubuntu-mono):
https://github.com/Bajoja/indicator-kdeconnect/tree/master/data/icons/ubuntu-mono-dark/status/22

**Comment by varlesh** [comment]
It's happened because on elementary icon theme not available **Inherits** option:
```
[Icon Theme]
Name=elementary
Comment=Smooth modern theme designed to be intuitive.

Example=directory-x-normal

#Directory list
Directories=actions/16
...
```
Add manual:
```
[Icon Theme]
Name=elementary
Comment=Smooth modern theme designed to be intuitive.
Inherits=ubuntu-mono-dark
```

**Comment by MrSadness** [comment]
Still the same, it did not work

**Comment by varlesh** [comment]
if change icon theme to ubuntu-mono-dark on elementary-tweaks - icon kdeconnect changed on tray?

**Comment by varlesh** [comment]
It should be used this icon:
![image](https://cloud.githubusercontent.com/assets/8083855/20655259/00d91f50-b532-11e6-87f3-5eddf1f7edc8.png)

**Comment by Bajoja** [comment]
At this time custom icons are only for ubuntu-mono,  if you use a different icons theme indicator-kdeconnect will use the default of the theme,  i think elementary support ubuntu-mono,  just select them from your system tweak configuration. 

If you want to use your custom icons,  I suggest you  to copy the icons on Ubuntu-mono folder to your /scalable/status/ folder of your icons, just how I made because my system don't support ubuntu-mono
